- name: vscode | Install apt-transport-https
  apt:
    name: apt-transport-https
    state: latest

- name: vscode | Setup Repository Keys
  apt_key:
    url: "{{item}}"
    state: present
  with_items:
    - https://packages.microsoft.com/keys/microsoft.asc

- name: vscode | Setup Repositories
  apt_repository:
    repo: "{{item}}"
    state: present
    filename: vscode
  with_items:
    - "deb [arch=amd64] http://packages.microsoft.com/repos/vscode stable main"

- name: vscode | Install Packages
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - code
