- hosts: all
  tasks:

    # setup yum repos

    - name: RPM Fusion - Free
      dnf:
        name: 'https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-25.noarch.rpm'
        state: present

    - name: RPM Fusion - Non-free
      dnf:
        name: 'https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-25.noarch.rpm'
        state: present

    - name: Google Chrome Repository
      dnf:
        name: 'https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm'
        state: present

    - name: Slack
      dnf:
        name: 'https://downloads.slack-edge.com/linux_releases/slack-2.4.2-0.1.fc21.x86_64.rpm'
        state: present

    - name: ZFS
      dnf:
        name: 'http://download.zfsonlinux.org/fedora/zfs-release.fc25.noarch.rpm'
        state: present


    # install packages

    - name: Install Ansible
      dnf:
        name: ansible
        state: latest

    - name: Install cargo
      dnf:
        name: cargo
        state: latest

    - name: Install clang
      dnf:
        name: clang
        state: latest

    - name: Install CTags
      dnf:
        name: ctags
        state: latest

    - name: Install Docker
      dnf:
        name: docker
        state: latest

    - name: Install Docker Compose
      dnf:
        name: docker-compose
        state: latest

    - name: Install Dropbox
      dnf:
        name: nautilus-dropbox
        state: latest

    - name: Install Git
      dnf:
        name: git
        state: latest

    - name: Install gnome-tweak-tool
      dnf:
        name: gnome-tweak-tool
        state: latest

    - name: Install Go
      dnf:
        name: golang
        state: latest

    - name: Install Google Chrome
      dnf:
        name: google-chrome
        state: latest

    - name: Install Java
      dnf:
        name: java-1.8.0-openjdk
        state: latest

    - name: Install jq
      dnf:
        name: jq
        state: latest

    - name: Install kernel-devel
      dnf:
        name: kernel-devel
        state: latest

    - name: Install libselinux-python
      dnf:
        name: libselinux-python
        state: latest

    - name: Install npm
      dnf:
        name: npm
        state: latest

    - name: Install pandoc
      dnf:
        name: pandoc
        state: latest

    - name: Install python-netaddr
      dnf:
        name: python-netaddr
        state: latest

    - name: Install Qt 5 Devel
      dnf:
        name: qt5-devel
        state: latest

    - name: Install redshift-gtk
      dnf:
        name: redshift-gtk
        state: latest

    - name: Install qtcreator
      dnf:
        name: qtcreator
        state: latest

    - name: Install rsync
      dnf:
        name: rsync
        state: latest

    - name: Install steam
      dnf:
        name: steam
        state: latest

    - name: Install sudo
      dnf:
        name: sudo
        state: latest

    - name: Install tig
      dnf:
        name: tig
        state: latest

    - name: Install tarsnap
      dnf:
        name: tarsnap
        state: latest

    - name: Install tmux
      dnf:
        name: tmux
        state: latest

    - name: Install vim-enhanced
      dnf:
        name: vim-enhanced
        state: latest

    - name: Install vim-X11
      dnf:
        name: vim-X11
        state: latest

    - name: Install ZFS
      dnf:
        name: zfs
        state: latest

    - name: Install ZSH
      dnf:
        name: zsh
        state: latest


    # pip packages

    - name: yq - YAML Query
      pip:
        name: yq


    # setup users and groups

    - name: Docker Group
      group:
        name: docker
        state: present
    - name: Add gary to docker
      user:
        name: gary
        groups: docker
        append: true


    - name: libvirt Group
      group:
        name: libvirt
        state: present
    - name: Add gary to libvirt
      user:
        name: gary
        groups: libvirt
        append: true


    # disable SELinux

    - name: Disable SELinux
      selinux:
        state: disabled


    # setup config files

    - name: Clear /etc/vimrc
      copy:
        src: etc/vimrc
        dest: /etc/vimrc
        mode: 0644
        force: yes

    - name: Install /etc/sudoers
      copy:
        src: etc/sudoers
        dest: /etc/sudoers
        mode: 0644
        force: yes
