# setup config files

- name: general | Install etc files
  copy:
    src: "general/files{{item}}"
    dest: "{{item}}"
    force: yes
  with_items:
    - /etc/nginx/sites-enabled/syncthing.conf
    - /etc/ssh/sshd_config
    - /etc/sudoers
    - /etc/vimrc

# setup users and groups

- name: general | Setup Groups
  group:
    name: "{{item}}"
    state: present
  with_items:
    - docker
    - wheel

- name: general | Setup Users
  user:
    name: "{{item}}"
    groups: docker,wheel
    append: true
  with_items:
    - gary

- name: general | Install authroized_keys
  authorized_key:
    user: "{{item}}"
    state: present
    key: "{{ lookup('file', '/home/gary/.ssh/id_rsa.pub') }}"
  with_items:
    - gary
    - root

# services

- name: general | Enable Daemons
  service:
    name: "{{item}}"
    enabled: yes
    state: started
  with_items:
    - docker
    - nginx
    - sshd
    - syncthing@gary
