---
  - hosts: workstations
    tasks:
    - include: 'workstation/workstation.yml'

  - hosts: openvpn_servers
    tasks:
    - include: 'openvpn/openvpn.yml'

  - hosts: plex_servers
    tasks:
    - include: 'plex_server/plex_server.yml'
