# setup Samba

- name: samba-ad-dc | Install Samba Packages
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - krb5-config
    - samba
    - smbclient
    - winbind

- name: samba-ad-dc | Install /etc/samba
  copy:
    src: "samba/files/etc/samba"
    dest: "/etc"
    mode: 0644
    force: yes

- name: samba-ad-dc | Install Kerberos Config
  file:
    src: /var/lib/samba/private/krb5.conf
    dest: /etc/krb5.conf
    state: link
    force: yes

- name: samba-ad-dc | Disable smbd Service
  systemd:
    name: smbd
    enabled: no
    state: stopped

- name: samba-ad-dc | Disable nmbd Service
  systemd:
    name: nmbd
    enabled: no
    state: stopped

- name: samba-ad-dc | Enable Samba Service
  systemd:
    name: samba-ad-dc
    enabled: yes
    masked: no
    state: started
