- name: plex_server | Install Packages
  apt:
    name: "{{item}}"
    state: latest
  with_items:
    - docker-ce

- name: plex_server | Pull Plex Image
  docker_image:
    name: plexinc/pms-docker:latest
    force: yes

- name: plex_server | Create Plex Container
  docker_container:
    name: Plex
    image: plexinc/pms-docker:latest
    state: started
    restart_policy: always
    network_mode: host
    env:
      PLEX_CLAIM: "America/North_Dakota/Center"
    volumes:
      - /pool0/plex/database:/config
      - /pool0/plex/transcode:/transcode
      - /pool0/plex/data:/data
      - /pool0/plex/media_libraries:/media_libraries
